### PR TITLE
Translation fixes, some new translations and removal of duplicate lines

### PR DESCRIPTION
**Pull request by ImFelixprogram**
This pull request contains:

- translations for some of the empty spaces
- translations for some english parts in german translations
- removing some duplicate lines from translations.txt

### CODE REVIEW

**Comment by ImFelixprogram** [comment]
Just looked at the english language repository again and some lines that I've removed for being duplicate were probably changed by a contributor when being translated (f.e. "Please copy the correct key file to the bootconfig directory on your USB Flash boot device or choose Purchase Key or Replace Key" [line 618] which should be "Please copy the correct key file to the config directory on your USB Flash boot device or choose Purchase Key or Replace Key" [former line 630] according to the english repository and that I've removed as duplicate because that wasn't translated while the first one was). Please wait before merging / checking until I've rechecked all removed duplicates and fixed ones where the original was changed and then translated like in that example.

**Comment by ImFelixprogram** [comment]
It seems like those came from the initial commit by @bergware when he added them to the repository - those aren't included in the english (en_US) repository by default but with a slightly different original key (like I showed above). 
So what about those?
Should that be changed to fit the en_US repository original 
or 
should they be left in and the en_US original be added back in and translated too?

For better understanding, affected keys are
(Format is: "New in de_DE" aka "Original in en_US which were also present in de_DE and removed by me as duplicate")

- "Please copy the correct key file to the bootconfig directory on your USB Flash boot device or choose Purchase Key or Replace Key" aka "Please copy the correct key file to the config directory on your USB Flash boot device or choose Purchase Key or Replace Key"
- "Please copy the correct key file to the bootconfig directory on your USB Flash boot device or choose Purchase Key" aka "Please copy the correct key file to the config directory on your USB Flash boot device or choose Purchase Key"
- "The key file should be located in the bootconfig directory on your USB Flash boot device" aka "Please remove all key files except the one you want to replace from the config directory on your USB Flash boot device"

For better understanding to german contributors:
Manche Zeilen, die ich als doppelt entfernt habe (genauer gesagt, die 3 oben aus dem Vergleich), waren anscheinend garnicht wirklich "doppelt" sondern heißen in übersetzter Form leicht anders (enthalten "bootconfig" anstatt "config"), diese heißen allerdings in der en_US repository so wie die bisher nicht übersetzten und von mir in diesem pull request entfernten Zeilen (die Zeilen mit "bootconfig" existieren in der en_US repository garnicht, nur die Zeilen mit "config"). Ich bin mir nun nicht sicher, was ich tun sollte. Die nicht in en_US vorhandenen Zeilen in de_DE so abändern, dass sie übereinstimmen oder diese so belassen und die Zeilen aus en_US wieder zu de_DE hinzufügen und übersetzen?

**Comment by bergware** [comment]
@spencerjunraid please wait with merging. I have a check first

**Comment by ImFelixprogram** [comment]
@bergware Thanks for having a look at it. I hope we can resolve this together

**Comment by spencerjunraid** [comment]
@bergware - holding.

**Comment by bergware** [comment]
I created a script which checks for and removes duplicate entries in the language files (it occurs in all languages, not only German).

There is now an updated translations.txt file on github with all duplicate entries removed.
You will need to work with this updated version and close this commit.

**Comment by ImFelixprogram** [comment]
Okay, will do. What about that three entries with "duplicates" that have only one word substituted but that occur only in the german translations (the one I stated above, which have the only difference in one saying "bootconfig" and the other saying "config")?
Lines would be

- 609 and 621
- 610 and 622
- 614 and 623
in translations.txt (the current version on master branch)

Did you find out if they're duplicates where someone made a mistake or if both are needed?

@bergware

**Comment by ImFelixprogram** [comment]
@bergware [Just a sanity ping for the message above because I edited that ping in and I can't verify if that triggered a notification after all]

**Comment by bergware** [comment]
_> What about that three entries with "duplicates" that have only one word substituted_

Yes, these are duplicates and happened because the text in the source code was adjusted, but the old text was already added to the German translation.

I made another update with these duplicates removed.

**Comment by ImFelixprogram** [comment]
Okay, that's nice, I'm closing this pull request now and creating a new one for the new translations only

**Pull request closed without merging**
