### PR TITLE
Plugins translation updates

### PR DESCRIPTION
**Pull request by kennymc-c**
Translation updates for some plugins

### CODE REVIEW

**Comment by ich777** [comment]
@spencerjunraid can be merged.
@kennymc-c Danke!

**Comment by kennymc-c** [comment]
Just translated the 2 new entries that came shortly after the OK for the merge. Maybe it's better to wait with new commits if there are open pull requests for the same files.

**Comment by kennymc-c** [comment]
@spencerjunraid Any reason why this has not been merged yet?

**Comment by spencerjunraid** [comment]
@kennymc-c - apologies, I was at a company off site last week and must have missed this. Will merge now. Thank you

**Pull request merged**
